### ISSUE TITLE
blowfish-tools new site error

### ISSUE THREAD

**Issue by xiaopindev** [nunocoracao/blowfish-tools#73]
Hello, I created the project with blowfish-tools new command and there was an error. How do I solve this problem?

The following is the log information generated by the CLI: 

PPM2-MacBook-Air Desktop % blowfish-tools new blowfish_web
✔ Hugo is available
✔ Git is available
✔ Folder ok...
✔ Hugo site created
✔ Git initialized
✔ Blowfish installed
⠋ Configuring BlowfishError: ENOENT: no such file or directory, lstat 'blowfish_web/themes/blowfish/config/_default'
    at lstatSync (node:fs:1640:25)
    at getStatsSync (node:internal/fs/cp/cp-sync:120:19)
    at checkPathsSync (node:internal/fs/cp/cp-sync:72:33)
    at cpSyncFn (node:internal/fs/cp/cp-sync:58:42)
    at Object.cpSync (node:fs:3077:3)
    at utils.directoryCopy (file:///usr/local/lib/node_modules/blowfish-tools/src/utils.js:101:8)
    at flow.configureNew (file:///usr/local/lib/node_modules/blowfish-tools/src/flow.js:116:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'blowfish_web/themes/blowfish/config/_default'
}

**Comment by nunocoracao** [comment]
Hello @xiaopindev I just tried on my mac and it seems to work. 
Are you running the command with enough permissions? What OS are you using?

![Screenshot 2024-07-17 at 12 42 01](https://github.com/user-attachments/assets/6fe484d3-c00d-48f3-b8cf-1e7a46e6f9e5)

**Comment by xiaopindev** [comment]
Hello, @nunocoracao . I found out it's my network instability. It can be created normally when the network is normal.
