### ISSUE TITLE
Project creation continues despite git submodule failure

### ISSUE THREAD

**Issue by Rami-Sabbagh** [nunocoracao/blowfish-tools#79]
Hello,
I've encountered this minor issue while using the tool, it would fail with this error:

```txt
~ blowfish-tools new testing-pool
✔ Hugo is available
✔ Git is available
✔ Folder ok...
✔ Hugo site created
✔ Git initialized
✔ Blowfish installed
⠋ Configuring BlowfishError: ENOENT: no such file or directory, lstat 'W:\Temporary\testing-pool\themes\blowfish\config\_default'
    at lstatSync (node:fs:1640:25)
    at getStatsSync (node:internal/fs/cp/cp-sync:120:19)
    at checkPathsSync (node:internal/fs/cp/cp-sync:72:33)
    at cpSyncFn (node:internal/fs/cp/cp-sync:58:42)
    at Object.cpSync (node:fs:3077:3)
    at utils.directoryCopy (file:///C:/Users/Rami/AppData/Roaming/npm/node_modules/blowfish-tools/src/utils.js:156:8)
    at flow.configureNew (file:///C:/Users/Rami/AppData/Roaming/npm/node_modules/blowfish-tools/src/flow.js:116:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'W:\\Temporary\\testing-pool\\themes\\blowfish\\config\\_default'
}
```

Initially thought it got outdated, but the blowfish project seems maintained.
After checking the cli code, it turns out the theme submodule failed to clone, but the tool continued anyway, to fail later when copying the default configuration files.

When trying to add the submodule manually, it would fail like this:

```txt
~ git submodule add --depth 1 -b main https://github.com/nunocoracao/blowfish.git themes/blowfish
Cloning into 'W:/Temporary/testing-pool/themes/blowfish'...
remote: Enumerating objects: 1320, done.
remote: Counting objects: 100% (1320/1320), done.
remote: Compressing objects: 100% (884/884), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 2338 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
fatal: clone of 'https://github.com/nunocoracao/blowfish.git' into submodule path 'W:/Temporary/testing-pool/themes/blowfish' failed
```
with a non-zero exit-code.

**Comment by pranavnasrani** [comment]
@Rami-Sabbagh please provide blowfish versions and hugo versions.

**my comment on #80 should help you**

however the error seems different. providing blowfish versions will help us to help you. .80 released couple of fixes, so maybe try now. i assume you are using Windows
